pipeline {
  agent any

  parameters {
        string(name: 'deployment_id', defaultValue: 'test1', description: 'Please specify deployment id (UUID)')
		choice(name: 'cloud_provider', choices: ['azure', 'gcp', 'aws'], description: 'Please specify Cloud Provide name')
		choice(name: 'blueprint_name', choices: ['centosserver', 'coreosserver', 'debianserver', 'opensuseserver', 'suseserver', 'ubuntuserver', 'win2016server', 'win2021server', 'ubuntuapache2server'], description: 'Provide blueprint name for provisioning' )
		booleanParam(name: 'application_blueprint', defaultValue: 'false', description: 'Please specify if this is application blueprint')
		string(name: 'resource_group_name', defaultValue: 'CMP', description: 'Please Azure Resource Group Name')
		string(name: 'vm_hostname', defaultValue: 'mycentonserver', description: 'Please host name for VM')
		string(name: 'vm_size', defaultValue: 'Standard_DS1_V2', description: 'Please size of VM')
		string(name: 'azure_subscription_id', defaultValue: 'e24e76dc-df5a-4add-b57b-6aa3f0eae0ee', description: 'Please specify Azure Subscription ID')
		string(name: 'azure_client_id', defaultValue: '49dc5041-2873-4ee7-9a05-33723de63dbf', description: 'Please specify Azure Client ID')
		string(name: 'azure_client_secret', defaultValue: 'VdgxkF~M3-Kl004gGOdc1SS7a-q4kC.Lkh', description: 'Please specify Azure Client secret')
		string(name: 'azure_tenant_id', defaultValue: '98f13429-d038-4e5e-85d8-846c6a963288', description: 'Please specify Azure Tenant ID')
		string(name: 'location', defaultValue: 'westus2', description: 'Please specify Azure location')
		string(name: 'nb_instances', defaultValue: '1', description: 'Please specify no. of instance to be deployed on Cloud')
		string(name: 'vnet_subnet_id', defaultValue: '/subscriptions/e24e76dc-df5a-4add-b57b-6aa3f0eae0ee/resourceGroups/CMP/providers/Microsoft.Network/virtualNetworks/CMP-vnet/subnets/default', description: 'Please specify Azure Subnet ID')
		booleanParam(name: 'data_disk', defaultValue: 'true', description: 'Please specify if you wish to add additonal persistent storage')
		string(name: 'data_disk_size_gb', defaultValue: '64', description: 'Please specify additonal persistent storage size in GB')
		string(name: 'tags', defaultValue: '{"environment":"dev","costcenter":"it","deployement_id":"${BUILD_ID}"}', description: 'Please specify tags to apply to resources')
		booleanParam(name: 'test_run', defaultValue: 'true', description: 'Please specify if this is test run')
    }
  stages {
	stage('Terraform Preparation') {
      steps {
	dir("blueprints/${blueprint_name}") {  
		replace_variable("resource_group_name", "${resource_group_name}")
		replace_variable("azure_subscription_id", "${azure_subscription_id}")
		replace_variable("azure_client_id", "${azure_client_id}")
		replace_variable("azure_client_secret", "${azure_client_secret}")
		replace_variable("azure_tenant_id", "${azure_tenant_id}")
		replace_variable("location", "${location}")
		replace_variable("nb_instances", "${nb_instances}")
		replace_variable("vnet_subnet_id", "${vnet_subnet_id}")
		replace_variable("data_disk", "${data_disk}")
		replace_variable("data_disk_size_gb", "${data_disk_size_gb}")
		replace_variable("vm_hostname", "${vm_hostname}")
		replace_variable("application_blueprint", "${application_blueprint}")
		replace_variable("vm_size", "${vm_size}")
		replace_tags("${tags}")
		sh "cat main.tf"
	  }
       }
    }
    stage('Terraform Init') {
      steps {
	dir("blueprints/${blueprint_name}") {  
		sh "terraform init -backend-config=\"conn_str=postgres://hcmp:Hcmp@123@10.160.128.110/hcmp?sslmode=disable\" -input=false"
		sh "terraform workspace new ${deployment_id}"
		sh "terraform workspace select  ${deployment_id}"
		sh "terraform workspace show"
		sh "terraform state pull"
	  }
       }
    }
    stage('Terraform Plan') {
      steps {
		dir("blueprints/${blueprint_name}") {   
			sh "terraform plan -out=tfplan"
			sh "terraform show -no-color tfplan > ${deployment_id}_tfplan.txt"
		}
      }
    }
   stage('Terraform Apply') {
      when {
		expression {
			return !params.test_run
		}
      }
      steps {
		dir("blueprints/${blueprint_name}") {   
			sh "terraform apply -input=false -auto-approve tfplan"
			sh "terraform output"
			sh "echo ***********************************"
			sh "echo state information"
			sh "echo ***********************************"
			sh "terraform show -json"
			sh "echo ***********************************"
		}
      }
	  post {
		failure {
			echo 'FAILED (in Terraform Apply stage - should not happen :))'
			script {
				dir("blueprints/${blueprint_name}") {
					def plan = readFile "${deployment_id}_tfplan.txt"
					input message: "Do you want to destroy the plan to rollback incomplete provisioning resources?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
					sh "terraform workspace select ${deployment_id}"
					sh "terraform destroy -input=false -auto-approve"
				}
            }
		}
	  }

    }
  stage('Terraform Destroy Approval') {
	   when {
		expression {
			return !params.test_run
		}
      }
	   steps {
		   dir("blueprints/${blueprint_name}") {  
            script {
                def plan = readFile "${deployment_id}_tfplan.txt"
                input message: "Do you want to destroy the plan?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
            }
		   }
        }
    }
  stage('Terraform Destroy') {
      when {
		expression {
			return !params.test_run
		}
      }
      steps {
		dir("blueprints/${blueprint_name}") {   
			sh "terraform workspace select ${deployment_id}"
			sh "terraform destroy -input=false -auto-approve"
		}
      }
    }
  }
  post {
        always {
			dir("blueprints/${blueprint_name}") {
					archiveArtifacts artifacts: "${deployment_id}_tfplan.txt"
					echo "Pipeline deployment id: ${deployment_id}"
					echo "Pipeline build_number: ${env.BUILD_NUMBER}"
					echo "Pipeline result: ${currentBuild.result}"
				  
				script {
				   output = sh(script: "PGPASSWORD='Hcmp@123' psql -h 10.160.128.110 -U hcmp -d hcmp -t -c \"select row_to_json(states) from terraform_remote_state.states where name = \'${deployment_id}\';\"",, returnStdout: true).trim()
				   url = "http://10.160.128.113:30260/api/v1/callback/jenkins/callback/"
				   echo "${output}"
				   
				  
				   responce = sh(script: "curl -X POST -H 'Content-Type: application/json' -d '{\"deploymentId\":\"${deployment_id}\",\"status\":\"${currentBuild.result}\"}' $url",returnStdout: true).trim()
				   echo "$responce"
		 
					echo "${output}"
				 }

				echo "${output}"
				cleanWs()
		   }
        }
    }
}

def replace_variable(String oldText, String newText) {
	def text = readFile file: "main.tf"
	text = text.replaceAll("%${oldText}%", "${newText}")
	writeFile file: "main.tf", text: text
}

@NonCPS
def replace_tags(txt){
	def lazyMap = new groovy.json.JsonSlurper().parseText(txt)
	def map = [:]
	for ( prop in lazyMap ) {
    	map[prop.key] = '"' + prop.value + '"'
	}
	def tf_tags = new StringBuilder().append("{")
	for(element in map) {
		tf_tags.append(element).append("\n")
	}
	tf_tags.append("}")
	replace_variable("tags", tf_tags.toString())
}
